services:
  - type: web
    name: e-com-store
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
